// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package globals

type Globals struct {
	WorkspaceID *string `pathParam:"style=simple,explode=false,name=workspace_id"`
}

func (g *Globals) GetWorkspaceID() *string {
	if g == nil {
		return nil
	}
	return g.WorkspaceID
}
