name: Generate

on: pull_request

jobs:
  build:
    name: Generate SDK
    runs-on: ubuntu-latest
    steps:
      - uses: speakeasy-api/sdk-generation-action
        with:
          speakeasy-version: latest
          openapi-doc-location: https://docs.speakeasyapi.dev/openapi.yaml
          github-access-token: test
          languages: |-
            - go
