// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tests

import (
	"testing"
)

func TestApiendpoints_DeleteAPIEndpoint(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step deleteApiEndpoint.test referencing operation deleteApiEndpoint not found in document`]")
}

func TestApiendpoints_FindAPIEndpoint(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step findApiEndpoint.test referencing operation findApiEndpoint not found in document`]")
}

func TestApiendpoints_GenerateOpenAPISpecForAPIEndpoint(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step generateOpenApiSpecForApiEndpoint.test referencing operation generateOpenApiSpecForApiEndpoint not found in document`]")
}

func TestApiendpoints_GeneratePostmanCollectionForAPIEndpoint(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step generatePostmanCollectionForApiEndpoint.test referencing operation generatePostmanCollectionForApiEndpoint not found in document`]")
}

func TestApiendpoints_GetAllAPIEndpoints(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step getAllApiEndpoints.test referencing operation getAllApiEndpoints not found in document`]")
}

func TestApiendpoints_GetAllForVersionAPIEndpoints(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step getAllForVersionApiEndpoints.test referencing operation getAllForVersionApiEndpoints not found in document`]")
}

func TestApiendpoints_GetAPIEndpoint(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step getApiEndpoint.test referencing operation getApiEndpoint not found in document`]")
}

func TestApiendpoints_UpsertAPIEndpoint(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step upsertApiEndpoint.test referencing operation upsertApiEndpoint not found in document`]")
}
