// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tests

import (
	"testing"
)

func TestMetadata_DeleteVersionMetadata(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step deleteVersionMetadata.test referencing operation deleteVersionMetadata not found in document`]")
}

func TestMetadata_GetVersionMetadata(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step getVersionMetadata.test referencing operation getVersionMetadata not found in document`]")
}

func TestMetadata_InsertVersionMetadata(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step insertVersionMetadata.test referencing operation insertVersionMetadata not found in document`]")
}
