// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tests

import (
	"context"
	speakeasyclientsdkgo "github.com/speakeasy-api/speakeasy-client-sdk-go/v3"
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/operations"
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/utils"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestPublishingtokens_GetPublishingTokenPublicMetadata(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("getPublishingTokenPublicMetadata")

	s := speakeasyclientsdkgo.New(
		speakeasyclientsdkgo.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		speakeasyclientsdkgo.WithClient(testHTTPClient),
		speakeasyclientsdkgo.WithSecurity(shared.Security{
			APIKey: speakeasyclientsdkgo.String("<YOUR_API_KEY_HERE>"),
		}),
	)

	res, err := s.PublishingTokens.ResolveMetadata(ctx, operations.GetPublishingTokenPublicMetadataRequest{
		TokenID: "<id>",
	})
	require.NoError(t, err)
	assert.Equal(t, 200, res.StatusCode)
	assert.NotNil(t, res.Object)
	assert.Equal(t, &operations.GetPublishingTokenPublicMetadataResponseBody{}, res.Object)

}
