// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tests

import (
	"testing"
)

func TestSchemas_DeleteSchema(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step deleteSchema.test referencing operation deleteSchema not found in document`]")
}

func TestSchemas_GetSchema(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step getSchema.test referencing operation getSchema not found in document`]")
}

func TestSchemas_GetSchemaDiff(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step getSchemaDiff.test referencing operation getSchemaDiff not found in document`]")
}

func TestSchemas_GetSchemaRevision(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step getSchemaRevision.test referencing operation getSchemaRevision not found in document`]")
}

func TestSchemas_GetSchemas(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step getSchemas.test referencing operation getSchemas not found in document`]")
}

func TestSchemas_RegisterSchema(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step registerSchema.test referencing operation registerSchema not found in document`]")
}
