// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ActivateSubscriptionNamespaceRequest struct {
	// The namespace name
	NamespaceName string `pathParam:"style=simple,explode=false,name=namespaceName"`
	// The existing subscription ID
	SubscriptionID string `pathParam:"style=simple,explode=false,name=subscriptionID"`
}

func (a *ActivateSubscriptionNamespaceRequest) GetNamespaceName() string {
	if a == nil {
		return ""
	}
	return a.NamespaceName
}

func (a *ActivateSubscriptionNamespaceRequest) GetSubscriptionID() string {
	if a == nil {
		return ""
	}
	return a.SubscriptionID
}

type ActivateSubscriptionNamespaceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (a *ActivateSubscriptionNamespaceResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *ActivateSubscriptionNamespaceResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *ActivateSubscriptionNamespaceResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}
