// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/utils"
	"net/http"
)

// ArchiveNamespaceRequestBody - Archived status
type ArchiveNamespaceRequestBody struct {
	Archived *bool `default:"true" json:"archived"`
}

func (a ArchiveNamespaceRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ArchiveNamespaceRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ArchiveNamespaceRequestBody) GetArchived() *bool {
	if a == nil {
		return nil
	}
	return a.Archived
}

type ArchiveNamespaceRequest struct {
	// Archived status
	RequestBody   *ArchiveNamespaceRequestBody `request:"mediaType=application/json"`
	NamespaceName string                       `pathParam:"style=simple,explode=false,name=namespace_name"`
}

func (a *ArchiveNamespaceRequest) GetRequestBody() *ArchiveNamespaceRequestBody {
	if a == nil {
		return nil
	}
	return a.RequestBody
}

func (a *ArchiveNamespaceRequest) GetNamespaceName() string {
	if a == nil {
		return ""
	}
	return a.NamespaceName
}

type ArchiveNamespaceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (a *ArchiveNamespaceResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *ArchiveNamespaceResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *ArchiveNamespaceResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}
