// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type CreateLanguageCheckoutSessionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	CreateCheckoutSessionResponse *shared.CreateCheckoutSessionResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *CreateLanguageCheckoutSessionResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateLanguageCheckoutSessionResponse) GetCreateCheckoutSessionResponse() *shared.CreateCheckoutSessionResponse {
	if c == nil {
		return nil
	}
	return c.CreateCheckoutSessionResponse
}

func (c *CreateLanguageCheckoutSessionResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateLanguageCheckoutSessionResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}
