// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type CreateWorkspaceTokenGlobals struct {
	WorkspaceID *string `pathParam:"style=simple,explode=false,name=workspace_id"`
}

func (c *CreateWorkspaceTokenGlobals) GetWorkspaceID() *string {
	if c == nil {
		return nil
	}
	return c.WorkspaceID
}

type CreateWorkspaceTokenRequest struct {
	WorkspaceToken shared.WorkspaceToken `request:"mediaType=application/json"`
	// Unique identifier of the workspace.
	WorkspaceID *string `pathParam:"style=simple,explode=false,name=workspace_id"`
}

func (c *CreateWorkspaceTokenRequest) GetWorkspaceToken() shared.WorkspaceToken {
	if c == nil {
		return shared.WorkspaceToken{}
	}
	return c.WorkspaceToken
}

func (c *CreateWorkspaceTokenRequest) GetWorkspaceID() *string {
	if c == nil {
		return nil
	}
	return c.WorkspaceID
}

type CreateWorkspaceTokenResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *CreateWorkspaceTokenResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateWorkspaceTokenResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateWorkspaceTokenResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}
