// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type DeactivateLanguageRequest struct {
	// The target language (e.g., typescript, python, go)
	Language string `pathParam:"style=simple,explode=false,name=language"`
}

func (d *DeactivateLanguageRequest) GetLanguage() string {
	if d == nil {
		return ""
	}
	return d.Language
}

type DeactivateLanguageResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	LanguageActivationResponse *shared.LanguageActivationResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeactivateLanguageResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeactivateLanguageResponse) GetLanguageActivationResponse() *shared.LanguageActivationResponse {
	if d == nil {
		return nil
	}
	return d.LanguageActivationResponse
}

func (d *DeactivateLanguageResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeactivateLanguageResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
