// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type DeleteBillingAddOnRequest struct {
	// The specific add-on to delete.
	AddOn shared.BillingAddOn `pathParam:"style=simple,explode=false,name=add_on"`
}

func (d *DeleteBillingAddOnRequest) GetAddOn() shared.BillingAddOn {
	if d == nil {
		return shared.BillingAddOn("")
	}
	return d.AddOn
}

type DeleteBillingAddOnResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeleteBillingAddOnResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteBillingAddOnResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteBillingAddOnResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
