// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"io"
	"net/http"
)

type DownloadSchemaRequest struct {
	// The ID of the Api to download the schema for.
	APIID string `pathParam:"style=simple,explode=false,name=apiID"`
	// The version ID of the Api to delete metadata for.
	VersionID string `pathParam:"style=simple,explode=false,name=versionID"`
}

func (o *DownloadSchemaRequest) GetAPIID() string {
	if o == nil {
		return ""
	}
	return o.APIID
}

func (o *DownloadSchemaRequest) GetVersionID() string {
	if o == nil {
		return ""
	}
	return o.VersionID
}

type DownloadSchemaResponse struct {
	// OK
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	TwoXXApplicationJSONSchema io.ReadCloser
	// OK
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	TwoXXApplicationXYamlSchema io.ReadCloser
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DownloadSchemaResponse) GetTwoXXApplicationJSONSchema() io.ReadCloser {
	if o == nil {
		return nil
	}
	return o.TwoXXApplicationJSONSchema
}

func (o *DownloadSchemaResponse) GetTwoXXApplicationXYamlSchema() io.ReadCloser {
	if o == nil {
		return nil
	}
	return o.TwoXXApplicationXYamlSchema
}

func (o *DownloadSchemaResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DownloadSchemaResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DownloadSchemaResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
