// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type GetAccessTokenRequest struct {
	// The workspace ID
	WorkspaceID string `queryParam:"style=form,explode=true,name=workspace_id"`
}

func (g *GetAccessTokenRequest) GetWorkspaceID() string {
	if g == nil {
		return ""
	}
	return g.WorkspaceID
}

type GetAccessTokenResponse struct {
	// OK
	AccessToken *shared.AccessToken
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetAccessTokenResponse) GetAccessToken() *shared.AccessToken {
	if g == nil {
		return nil
	}
	return g.AccessToken
}

func (g *GetAccessTokenResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetAccessTokenResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetAccessTokenResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
