// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type GetBillingAddOnsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	OrganizationBillingAddOnResponse *shared.OrganizationBillingAddOnResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetBillingAddOnsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetBillingAddOnsResponse) GetOrganizationBillingAddOnResponse() *shared.OrganizationBillingAddOnResponse {
	if o == nil {
		return nil
	}
	return o.OrganizationBillingAddOnResponse
}

func (o *GetBillingAddOnsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetBillingAddOnsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
