// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"io"
	"net/http"
)

type GetBlobRequest struct {
	Digest           string `pathParam:"style=simple,explode=false,name=digest"`
	NamespaceName    string `pathParam:"style=simple,explode=false,name=namespace_name"`
	OrganizationSlug string `pathParam:"style=simple,explode=false,name=organization_slug"`
	WorkspaceSlug    string `pathParam:"style=simple,explode=false,name=workspace_slug"`
}

func (g *GetBlobRequest) GetDigest() string {
	if g == nil {
		return ""
	}
	return g.Digest
}

func (g *GetBlobRequest) GetNamespaceName() string {
	if g == nil {
		return ""
	}
	return g.NamespaceName
}

func (g *GetBlobRequest) GetOrganizationSlug() string {
	if g == nil {
		return ""
	}
	return g.OrganizationSlug
}

func (g *GetBlobRequest) GetWorkspaceSlug() string {
	if g == nil {
		return ""
	}
	return g.WorkspaceSlug
}

type GetBlobResponse struct {
	// OK
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	Blob io.ReadCloser
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetBlobResponse) GetBlob() io.ReadCloser {
	if g == nil {
		return nil
	}
	return g.Blob
}

func (g *GetBlobResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetBlobResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetBlobResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
