// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type GetGitHubActionRequest struct {
	Org  string `queryParam:"style=form,explode=true,name=org"`
	Repo string `queryParam:"style=form,explode=true,name=repo"`
	// The targetName of the workflow target.
	TargetName *string `queryParam:"style=form,explode=true,name=targetName"`
}

func (g *GetGitHubActionRequest) GetOrg() string {
	if g == nil {
		return ""
	}
	return g.Org
}

func (g *GetGitHubActionRequest) GetRepo() string {
	if g == nil {
		return ""
	}
	return g.Repo
}

func (g *GetGitHubActionRequest) GetTargetName() *string {
	if g == nil {
		return nil
	}
	return g.TargetName
}

type GetGitHubActionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	GithubGetActionResponse *shared.GithubGetActionResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetGitHubActionResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetGitHubActionResponse) GetGithubGetActionResponse() *shared.GithubGetActionResponse {
	if g == nil {
		return nil
	}
	return g.GithubGetActionResponse
}

func (g *GetGitHubActionResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetGitHubActionResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
