// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type GetNamespacesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	GetNamespacesResponse *shared.GetNamespacesResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetNamespacesResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetNamespacesResponse) GetGetNamespacesResponse() *shared.GetNamespacesResponse {
	if g == nil {
		return nil
	}
	return g.GetNamespacesResponse
}

func (g *GetNamespacesResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetNamespacesResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
