// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type GetOrganizationUsageResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	OrganizationUsageResponse *shared.OrganizationUsageResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetOrganizationUsageResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetOrganizationUsageResponse) GetOrganizationUsageResponse() *shared.OrganizationUsageResponse {
	if g == nil {
		return nil
	}
	return g.OrganizationUsageResponse
}

func (g *GetOrganizationUsageResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetOrganizationUsageResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
