// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/utils"
	"net/http"
	"time"
)

type GetPublishingTokenPublicMetadataRequest struct {
	// Unique identifier of the publishing token.
	TokenID string `pathParam:"style=simple,explode=false,name=tokenID"`
}

func (g *GetPublishingTokenPublicMetadataRequest) GetTokenID() string {
	if g == nil {
		return ""
	}
	return g.TokenID
}

// GetPublishingTokenPublicMetadataResponseBody - OK
type GetPublishingTokenPublicMetadataResponseBody struct {
	OrganizationID *string    `json:"organization_id,omitempty"`
	TargetID       *string    `json:"target_id,omitempty"`
	TargetResource *string    `json:"target_resource,omitempty"`
	ValidUntil     *time.Time `json:"valid_until,omitempty"`
	WorkspaceID    *string    `json:"workspace_id,omitempty"`
}

func (g GetPublishingTokenPublicMetadataResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPublishingTokenPublicMetadataResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetPublishingTokenPublicMetadataResponseBody) GetOrganizationID() *string {
	if g == nil {
		return nil
	}
	return g.OrganizationID
}

func (g *GetPublishingTokenPublicMetadataResponseBody) GetTargetID() *string {
	if g == nil {
		return nil
	}
	return g.TargetID
}

func (g *GetPublishingTokenPublicMetadataResponseBody) GetTargetResource() *string {
	if g == nil {
		return nil
	}
	return g.TargetResource
}

func (g *GetPublishingTokenPublicMetadataResponseBody) GetValidUntil() *time.Time {
	if g == nil {
		return nil
	}
	return g.ValidUntil
}

func (g *GetPublishingTokenPublicMetadataResponseBody) GetWorkspaceID() *string {
	if g == nil {
		return nil
	}
	return g.WorkspaceID
}

type GetPublishingTokenPublicMetadataResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *GetPublishingTokenPublicMetadataResponseBody
}

func (g *GetPublishingTokenPublicMetadataResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetPublishingTokenPublicMetadataResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetPublishingTokenPublicMetadataResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetPublishingTokenPublicMetadataResponse) GetObject() *GetPublishingTokenPublicMetadataResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
