// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type GetPublishingTokenByIDRequest struct {
	// Unique identifier of the publishing token.
	TokenID string `pathParam:"style=simple,explode=false,name=tokenID"`
}

func (g *GetPublishingTokenByIDRequest) GetTokenID() string {
	if g == nil {
		return ""
	}
	return g.TokenID
}

type GetPublishingTokenByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	PublishingToken *shared.PublishingToken
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetPublishingTokenByIDResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetPublishingTokenByIDResponse) GetPublishingToken() *shared.PublishingToken {
	if g == nil {
		return nil
	}
	return g.PublishingToken
}

func (g *GetPublishingTokenByIDResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetPublishingTokenByIDResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
