// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type GetRevisionsRequest struct {
	NamespaceName string `pathParam:"style=simple,explode=false,name=namespace_name"`
	// Token to retrieve the next page of results
	NextPageToken *string `queryParam:"style=form,explode=true,name=next_page_token"`
}

func (g *GetRevisionsRequest) GetNamespaceName() string {
	if g == nil {
		return ""
	}
	return g.NamespaceName
}

func (g *GetRevisionsRequest) GetNextPageToken() *string {
	if g == nil {
		return nil
	}
	return g.NextPageToken
}

type GetRevisionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	GetRevisionsResponse *shared.GetRevisionsResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetRevisionsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetRevisionsResponse) GetGetRevisionsResponse() *shared.GetRevisionsResponse {
	if g == nil {
		return nil
	}
	return g.GetRevisionsResponse
}

func (g *GetRevisionsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetRevisionsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
