// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type GetSchemaStoreItemRequestBody struct {
	ID *string `json:"id,omitempty"`
}

func (g *GetSchemaStoreItemRequestBody) GetID() *string {
	if g == nil {
		return nil
	}
	return g.ID
}

type GetSchemaStoreItemResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	SchemaStoreItem *shared.SchemaStoreItem
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetSchemaStoreItemResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetSchemaStoreItemResponse) GetSchemaStoreItem() *shared.SchemaStoreItem {
	if g == nil {
		return nil
	}
	return g.SchemaStoreItem
}

func (g *GetSchemaStoreItemResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetSchemaStoreItemResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
