// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type GetWorkspaceTeamGlobals struct {
	WorkspaceID *string `pathParam:"style=simple,explode=false,name=workspace_id"`
}

func (g *GetWorkspaceTeamGlobals) GetWorkspaceID() *string {
	if g == nil {
		return nil
	}
	return g.WorkspaceID
}

type GetWorkspaceTeamRequest struct {
	// Unique identifier of the workspace.
	WorkspaceID *string `pathParam:"style=simple,explode=false,name=workspace_id"`
}

func (g *GetWorkspaceTeamRequest) GetWorkspaceID() *string {
	if g == nil {
		return nil
	}
	return g.WorkspaceID
}

type GetWorkspaceTeamResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	WorkspaceTeamResponse *shared.WorkspaceTeamResponse
}

func (g *GetWorkspaceTeamResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetWorkspaceTeamResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetWorkspaceTeamResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetWorkspaceTeamResponse) GetWorkspaceTeamResponse() *shared.WorkspaceTeamResponse {
	if g == nil {
		return nil
	}
	return g.WorkspaceTeamResponse
}
