// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/utils"
	"net/http"
	"time"
)

type GetWorkspaceEventsByTargetGlobals struct {
	WorkspaceID *string `pathParam:"style=simple,explode=false,name=workspace_id"`
}

func (g *GetWorkspaceEventsByTargetGlobals) GetWorkspaceID() *string {
	if g == nil {
		return nil
	}
	return g.WorkspaceID
}

type GetWorkspaceEventsByTargetRequest struct {
	// Filter to only return events created after this timestamp
	AfterCreatedAt *time.Time `queryParam:"style=form,explode=true,name=after_created_at"`
	// Filter to only return events corresponding to a particular gen_lock_id (gen_lock_id uniquely identifies a target)
	TargetID string `pathParam:"style=simple,explode=false,name=target_id"`
	// Unique identifier of the workspace.
	WorkspaceID *string `pathParam:"style=simple,explode=false,name=workspace_id"`
}

func (g GetWorkspaceEventsByTargetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetWorkspaceEventsByTargetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetWorkspaceEventsByTargetRequest) GetAfterCreatedAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.AfterCreatedAt
}

func (g *GetWorkspaceEventsByTargetRequest) GetTargetID() string {
	if g == nil {
		return ""
	}
	return g.TargetID
}

func (g *GetWorkspaceEventsByTargetRequest) GetWorkspaceID() *string {
	if g == nil {
		return nil
	}
	return g.WorkspaceID
}

type GetWorkspaceEventsByTargetResponse struct {
	// Success
	CliEventBatch []shared.CliEvent
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetWorkspaceEventsByTargetResponse) GetCliEventBatch() []shared.CliEvent {
	if g == nil {
		return nil
	}
	return g.CliEventBatch
}

func (g *GetWorkspaceEventsByTargetResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetWorkspaceEventsByTargetResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetWorkspaceEventsByTargetResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
