// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type GetWorkspaceAccessRequest struct {
	// Unique identifier of the generation target.
	GenLockID *string `queryParam:"style=form,explode=true,name=genLockId"`
	// Skip side-effects like incrementing metrics.
	Passive *bool `queryParam:"style=form,explode=true,name=passive"`
	// The type of the generated target.
	TargetType *string `queryParam:"style=form,explode=true,name=targetType"`
}

func (g *GetWorkspaceAccessRequest) GetGenLockID() *string {
	if g == nil {
		return nil
	}
	return g.GenLockID
}

func (g *GetWorkspaceAccessRequest) GetPassive() *bool {
	if g == nil {
		return nil
	}
	return g.Passive
}

func (g *GetWorkspaceAccessRequest) GetTargetType() *string {
	if g == nil {
		return nil
	}
	return g.TargetType
}

type GetWorkspaceAccessResponse struct {
	// OK
	AccessDetails *shared.AccessDetails
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetWorkspaceAccessResponse) GetAccessDetails() *shared.AccessDetails {
	if g == nil {
		return nil
	}
	return g.AccessDetails
}

func (g *GetWorkspaceAccessResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetWorkspaceAccessResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetWorkspaceAccessResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
