// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type GithubCheckPublishingPRsRequest struct {
	GenerateGenLockID string `queryParam:"style=form,explode=true,name=generate_gen_lock_id"`
	Org               string `queryParam:"style=form,explode=true,name=org"`
	Repo              string `queryParam:"style=form,explode=true,name=repo"`
}

func (g *GithubCheckPublishingPRsRequest) GetGenerateGenLockID() string {
	if g == nil {
		return ""
	}
	return g.GenerateGenLockID
}

func (g *GithubCheckPublishingPRsRequest) GetOrg() string {
	if g == nil {
		return ""
	}
	return g.Org
}

func (g *GithubCheckPublishingPRsRequest) GetRepo() string {
	if g == nil {
		return ""
	}
	return g.Repo
}

type GithubCheckPublishingPRsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	GithubPublishingPRResponse *shared.GithubPublishingPRResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GithubCheckPublishingPRsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GithubCheckPublishingPRsResponse) GetGithubPublishingPRResponse() *shared.GithubPublishingPRResponse {
	if g == nil {
		return nil
	}
	return g.GithubPublishingPRResponse
}

func (g *GithubCheckPublishingPRsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GithubCheckPublishingPRsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
