// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type GithubCheckPublishingSecretsRequest struct {
	GenerateGenLockID string `queryParam:"style=form,explode=true,name=generate_gen_lock_id"`
}

func (g *GithubCheckPublishingSecretsRequest) GetGenerateGenLockID() string {
	if g == nil {
		return ""
	}
	return g.GenerateGenLockID
}

type GithubCheckPublishingSecretsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	GithubMissingPublishingSecretsResponse *shared.GithubMissingPublishingSecretsResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GithubCheckPublishingSecretsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GithubCheckPublishingSecretsResponse) GetGithubMissingPublishingSecretsResponse() *shared.GithubMissingPublishingSecretsResponse {
	if g == nil {
		return nil
	}
	return g.GithubMissingPublishingSecretsResponse
}

func (g *GithubCheckPublishingSecretsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GithubCheckPublishingSecretsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
