// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type HandleCheckoutCallbackRequest struct {
	// The Stripe checkout session ID
	SessionID string `queryParam:"style=form,explode=true,name=session_id"`
}

func (h *HandleCheckoutCallbackRequest) GetSessionID() string {
	if h == nil {
		return ""
	}
	return h.SessionID
}

type HandleCheckoutCallbackResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (h *HandleCheckoutCallbackResponse) GetContentType() string {
	if h == nil {
		return ""
	}
	return h.ContentType
}

func (h *HandleCheckoutCallbackResponse) GetHeaders() map[string][]string {
	if h == nil {
		return map[string][]string{}
	}
	return h.Headers
}

func (h *HandleCheckoutCallbackResponse) GetStatusCode() int {
	if h == nil {
		return 0
	}
	return h.StatusCode
}

func (h *HandleCheckoutCallbackResponse) GetRawResponse() *http.Response {
	if h == nil {
		return nil
	}
	return h.RawResponse
}
