// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type LinkGithubAccessRequest struct {
	GithubOidcToken *string `queryParam:"style=form,explode=true,name=github_oidc_token"`
	GithubOrg       *string `queryParam:"style=form,explode=true,name=github_org"`
	InstallationID  *string `queryParam:"style=form,explode=true,name=installation_id"`
}

func (l *LinkGithubAccessRequest) GetGithubOidcToken() *string {
	if l == nil {
		return nil
	}
	return l.GithubOidcToken
}

func (l *LinkGithubAccessRequest) GetGithubOrg() *string {
	if l == nil {
		return nil
	}
	return l.GithubOrg
}

func (l *LinkGithubAccessRequest) GetInstallationID() *string {
	if l == nil {
		return nil
	}
	return l.InstallationID
}

type LinkGithubAccessResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (l *LinkGithubAccessResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *LinkGithubAccessResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *LinkGithubAccessResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}
