// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type RevokeUserAccessToWorkspaceGlobals struct {
	WorkspaceID *string `pathParam:"style=simple,explode=false,name=workspace_id"`
}

func (r *RevokeUserAccessToWorkspaceGlobals) GetWorkspaceID() *string {
	if r == nil {
		return nil
	}
	return r.WorkspaceID
}

type RevokeUserAccessToWorkspaceRequest struct {
	// Unique identifier of the user.
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
	// Unique identifier of the workspace.
	WorkspaceID *string `pathParam:"style=simple,explode=false,name=workspace_id"`
}

func (r *RevokeUserAccessToWorkspaceRequest) GetUserID() string {
	if r == nil {
		return ""
	}
	return r.UserID
}

func (r *RevokeUserAccessToWorkspaceRequest) GetWorkspaceID() *string {
	if r == nil {
		return nil
	}
	return r.WorkspaceID
}

type RevokeUserAccessToWorkspaceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (r *RevokeUserAccessToWorkspaceResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *RevokeUserAccessToWorkspaceResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *RevokeUserAccessToWorkspaceResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}
