// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

// SetVisibilityRequestBody - Namespace visibility
type SetVisibilityRequestBody struct {
	Public bool `json:"public"`
}

func (o *SetVisibilityRequestBody) GetPublic() bool {
	if o == nil {
		return false
	}
	return o.Public
}

type SetVisibilityRequest struct {
	// Namespace visibility
	RequestBody   *SetVisibilityRequestBody `request:"mediaType=application/json"`
	NamespaceName string                    `pathParam:"style=simple,explode=false,name=namespace_name"`
}

func (o *SetVisibilityRequest) GetRequestBody() *SetVisibilityRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *SetVisibilityRequest) GetNamespaceName() string {
	if o == nil {
		return ""
	}
	return o.NamespaceName
}

type SetVisibilityResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *SetVisibilityResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SetVisibilityResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SetVisibilityResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
