// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type SetWorkspaceFeatureFlagsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	WorkspaceFeatureFlagResponse *shared.WorkspaceFeatureFlagResponse
}

func (s *SetWorkspaceFeatureFlagsResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SetWorkspaceFeatureFlagsResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SetWorkspaceFeatureFlagsResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}

func (s *SetWorkspaceFeatureFlagsResponse) GetWorkspaceFeatureFlagResponse() *shared.WorkspaceFeatureFlagResponse {
	if s == nil {
		return nil
	}
	return s.WorkspaceFeatureFlagResponse
}
