// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"io"
	"net/http"
)

type Schema struct {
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content  any    `multipartForm:"content"`
	FileName string `multipartForm:"name=fileName"`
}

func (s *Schema) GetContent() any {
	if s == nil {
		return nil
	}
	return s.Content
}

func (s *Schema) GetFileName() string {
	if s == nil {
		return ""
	}
	return s.FileName
}

// SuggestOpenAPIRequestBody - The schema file to upload provided as a multipart/form-data file segment.
type SuggestOpenAPIRequestBody struct {
	Opts   *shared.SuggestOptsOld `multipartForm:"name=opts,json"`
	Schema Schema                 `multipartForm:"file,name=schema"`
}

func (s *SuggestOpenAPIRequestBody) GetOpts() *shared.SuggestOptsOld {
	if s == nil {
		return nil
	}
	return s.Opts
}

func (s *SuggestOpenAPIRequestBody) GetSchema() Schema {
	if s == nil {
		return Schema{}
	}
	return s.Schema
}

type SuggestOpenAPIRequest struct {
	// The schema file to upload provided as a multipart/form-data file segment.
	RequestBody SuggestOpenAPIRequestBody `request:"mediaType=multipart/form-data"`
	XSessionID  string                    `header:"style=simple,explode=false,name=x-session-id"`
}

func (s *SuggestOpenAPIRequest) GetRequestBody() SuggestOpenAPIRequestBody {
	if s == nil {
		return SuggestOpenAPIRequestBody{}
	}
	return s.RequestBody
}

func (s *SuggestOpenAPIRequest) GetXSessionID() string {
	if s == nil {
		return ""
	}
	return s.XSessionID
}

type SuggestOpenAPIResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// An overlay containing the suggested spec modifications.
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	Schema io.ReadCloser
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (s *SuggestOpenAPIResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SuggestOpenAPIResponse) GetSchema() io.ReadCloser {
	if s == nil {
		return nil
	}
	return s.Schema
}

func (s *SuggestOpenAPIResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SuggestOpenAPIResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}
