// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type UpdateWorkspaceSettingsGlobals struct {
	WorkspaceID *string `pathParam:"style=simple,explode=false,name=workspace_id"`
}

func (u *UpdateWorkspaceSettingsGlobals) GetWorkspaceID() *string {
	if u == nil {
		return nil
	}
	return u.WorkspaceID
}

type UpdateWorkspaceSettingsRequest struct {
	// The workspace settings to update.
	WorkspaceSettings shared.WorkspaceSettings `request:"mediaType=application/json"`
	// Unique identifier of the workspace.
	WorkspaceID *string `pathParam:"style=simple,explode=false,name=workspace_id"`
}

func (u *UpdateWorkspaceSettingsRequest) GetWorkspaceSettings() shared.WorkspaceSettings {
	if u == nil {
		return shared.WorkspaceSettings{}
	}
	return u.WorkspaceSettings
}

func (u *UpdateWorkspaceSettingsRequest) GetWorkspaceID() *string {
	if u == nil {
		return nil
	}
	return u.WorkspaceID
}

type UpdateWorkspaceSettingsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (u *UpdateWorkspaceSettingsResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateWorkspaceSettingsResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateWorkspaceSettingsResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}
