// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BillingEmailRequest struct {
	// The billing email address to set
	BillingEmail string `json:"billing_email"`
}

func (o *BillingEmailRequest) GetBillingEmail() string {
	if o == nil {
		return ""
	}
	return o.BillingEmail
}
