// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Diagnostic struct {
	// Message describing the issue
	Message string `json:"message"`
	// Schema path to the issue
	Path []string `json:"path"`
	// Issue type
	Type string `json:"type"`
	// Help message for how to fix the issue
	HelpMessage *string `json:"helpMessage,omitempty"`
}

func (o *Diagnostic) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *Diagnostic) GetPath() []string {
	if o == nil {
		return []string{}
	}
	return o.Path
}

func (o *Diagnostic) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *Diagnostic) GetHelpMessage() *string {
	if o == nil {
		return nil
	}
	return o.HelpMessage
}
