// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetLanguagesResponse struct {
	// List of language billing configurations
	Languages []LanguageResponse `json:"languages"`
}

func (o *GetLanguagesResponse) GetLanguages() []LanguageResponse {
	if o == nil {
		return []LanguageResponse{}
	}
	return o.Languages
}
