// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetRevisionsResponse struct {
	Items         []Revision `json:"items"`
	NextPageToken string     `json:"next_page_token"`
}

func (o *GetRevisionsResponse) GetItems() []Revision {
	if o == nil {
		return []Revision{}
	}
	return o.Items
}

func (o *GetRevisionsResponse) GetNextPageToken() string {
	if o == nil {
		return ""
	}
	return o.NextPageToken
}
