// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GithubGetActionResponse - response to a getting the latest action run on a GitHub request
type GithubGetActionResponse struct {
	// The URL for latest action run if available
	RunURL *string `json:"run_url,omitempty"`
	// The status of the latest action run if available
	RunStatus *string `json:"run_status,omitempty"`
}

func (o *GithubGetActionResponse) GetRunURL() *string {
	if o == nil {
		return nil
	}
	return o.RunURL
}

func (o *GithubGetActionResponse) GetRunStatus() *string {
	if o == nil {
		return nil
	}
	return o.RunStatus
}
