// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// LanguageBillingBreakdown - Contains the billing breakdown for a single language
type LanguageBillingBreakdown struct {
	// The generated SDK language
	Language string `json:"language"`
	// Number of operations from the latest generation event for this language
	OperationCount int64 `json:"operation_count"`
	// Number of generated SDK targets for this language
	TargetCount int64 `json:"target_count"`
	// Total billable units contributed by targets in this language
	BillableUnits int64 `json:"billable_units"`
	// List of generated targets for this language
	Targets []TargetBillingBreakdown `json:"targets"`
}

func (o *LanguageBillingBreakdown) GetLanguage() string {
	if o == nil {
		return ""
	}
	return o.Language
}

func (o *LanguageBillingBreakdown) GetOperationCount() int64 {
	if o == nil {
		return 0
	}
	return o.OperationCount
}

func (o *LanguageBillingBreakdown) GetTargetCount() int64 {
	if o == nil {
		return 0
	}
	return o.TargetCount
}

func (o *LanguageBillingBreakdown) GetBillableUnits() int64 {
	if o == nil {
		return 0
	}
	return o.BillableUnits
}

func (o *LanguageBillingBreakdown) GetTargets() []TargetBillingBreakdown {
	if o == nil {
		return []TargetBillingBreakdown{}
	}
	return o.Targets
}
