// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LanguageActivationResponse struct {
	// Whether the operation was successful
	Success bool `json:"success"`
	// If true, user must complete checkout
	RequiresCheckout *bool `json:"requires_checkout,omitempty"`
	// The target language
	Language string `json:"language"`
	// The billing status of a language
	BillingStatus *LanguageBillingStatus `json:"billing_status,omitempty"`
	// Whether the language is deactivated
	Deactivated bool `json:"deactivated"`
	// Additional message about the operation
	Message *string `json:"message,omitempty"`
}

func (o *LanguageActivationResponse) GetSuccess() bool {
	if o == nil {
		return false
	}
	return o.Success
}

func (o *LanguageActivationResponse) GetRequiresCheckout() *bool {
	if o == nil {
		return nil
	}
	return o.RequiresCheckout
}

func (o *LanguageActivationResponse) GetLanguage() string {
	if o == nil {
		return ""
	}
	return o.Language
}

func (o *LanguageActivationResponse) GetBillingStatus() *LanguageBillingStatus {
	if o == nil {
		return nil
	}
	return o.BillingStatus
}

func (o *LanguageActivationResponse) GetDeactivated() bool {
	if o == nil {
		return false
	}
	return o.Deactivated
}

func (o *LanguageActivationResponse) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}
