// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
	"time"
)

type LanguageResponse struct {
	// The target language (e.g., typescript, python, go)
	Language string `json:"language"`
	// The billing status of a language
	BillingStatus *LanguageBillingStatus `json:"billing_status,omitempty"`
	// When the trial ends (if applicable)
	TrialEndsAt *time.Time `json:"trial_ends_at,omitempty"`
	// Whether the language is deactivated
	Deactivated bool `json:"deactivated"`
	// Whether the language can be deactivated (false if within 2-week cooldown)
	CanDeactivate bool `json:"can_deactivate"`
}

func (l LanguageResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LanguageResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"language", "deactivated", "can_deactivate"}); err != nil {
		return err
	}
	return nil
}

func (o *LanguageResponse) GetLanguage() string {
	if o == nil {
		return ""
	}
	return o.Language
}

func (o *LanguageResponse) GetBillingStatus() *LanguageBillingStatus {
	if o == nil {
		return nil
	}
	return o.BillingStatus
}

func (o *LanguageResponse) GetTrialEndsAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.TrialEndsAt
}

func (o *LanguageResponse) GetDeactivated() bool {
	if o == nil {
		return false
	}
	return o.Deactivated
}

func (o *LanguageResponse) GetCanDeactivate() bool {
	if o == nil {
		return false
	}
	return o.CanDeactivate
}
