// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type License struct {
	Identifier *string `json:"identifier,omitempty"`
}

func (o *License) GetIdentifier() *string {
	if o == nil {
		return nil
	}
	return o.Identifier
}

type OASInfo struct {
	Title       string  `json:"title"`
	Summary     string  `json:"summary"`
	Description string  `json:"description"`
	Version     string  `json:"version"`
	License     License `json:"license"`
}

func (o *OASInfo) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *OASInfo) GetSummary() string {
	if o == nil {
		return ""
	}
	return o.Summary
}

func (o *OASInfo) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *OASInfo) GetVersion() string {
	if o == nil {
		return ""
	}
	return o.Version
}

func (o *OASInfo) GetLicense() License {
	if o == nil {
		return License{}
	}
	return o.License
}
