// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	APIKey              *string `security:"scheme,type=apiKey,subtype=header,name=x-api-key"`
	WorkspaceIdentifier *string `security:"scheme,type=apiKey,subtype=header,name=x-workspace-identifier"`
	Bearer              *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *Security) GetAPIKey() *string {
	if o == nil {
		return nil
	}
	return o.APIKey
}

func (o *Security) GetWorkspaceIdentifier() *string {
	if o == nil {
		return nil
	}
	return o.WorkspaceIdentifier
}

func (o *Security) GetBearer() *string {
	if o == nil {
		return nil
	}
	return o.Bearer
}
