// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Server - A server as defined in an OpenAPI document
type Server struct {
	URL         string `json:"url"`
	Description string `json:"description"`
	// The x-speakeasy-server-id of the server
	ID *string `json:"id,omitempty"`
}

func (o *Server) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *Server) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *Server) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}
