// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ShortURL struct {
	FullURL  string `json:"full_url"`
	ShortURL string `json:"short_url"`
}

func (o *ShortURL) GetFullURL() string {
	if o == nil {
		return ""
	}
	return o.FullURL
}

func (o *ShortURL) GetShortURL() string {
	if o == nil {
		return ""
	}
	return o.ShortURL
}
