// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SSOMetadata - SSO metadata for a workspace
type SSOMetadata struct {
	SsoActivated bool     `json:"sso_activated"`
	SsoDomains   []string `json:"sso_domains"`
}

func (o *SSOMetadata) GetSsoActivated() bool {
	if o == nil {
		return false
	}
	return o.SsoActivated
}

func (o *SSOMetadata) GetSsoDomains() []string {
	if o == nil {
		return []string{}
	}
	return o.SsoDomains
}
