// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SuggestItemsRequestBody struct {
	// The prompt to use for the suggestion. Think of this as the "preamble".
	Prompt string `json:"prompt"`
	// The list of "things" to get suggestions for. One suggestion will be returned for each item in the list.
	Items []string `json:"items"`
}

func (o *SuggestItemsRequestBody) GetPrompt() string {
	if o == nil {
		return ""
	}
	return o.Prompt
}

func (o *SuggestItemsRequestBody) GetItems() []string {
	if o == nil {
		return []string{}
	}
	return o.Items
}
