// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateLanguageCheckoutSessionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	CreateCheckoutSessionResponse *components.CreateCheckoutSessionResponse
}

func (o *CreateLanguageCheckoutSessionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateLanguageCheckoutSessionResponse) GetCreateCheckoutSessionResponse() *components.CreateCheckoutSessionResponse {
	if o == nil {
		return nil
	}
	return o.CreateCheckoutSessionResponse
}
