// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateWorkspaceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Workspace *components.Workspace
}

func (o *CreateWorkspaceResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateWorkspaceResponse) GetWorkspace() *components.Workspace {
	if o == nil {
		return nil
	}
	return o.Workspace
}
