// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreatePublishingTokenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PublishingToken *components.PublishingToken
}

func (o *CreatePublishingTokenResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreatePublishingTokenResponse) GetPublishingToken() *components.PublishingToken {
	if o == nil {
		return nil
	}
	return o.PublishingToken
}
