// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeactivateLanguageRequest struct {
	// The target language (e.g., typescript, python, go)
	Language string `pathParam:"style=simple,explode=false,name=language"`
}

func (o *DeactivateLanguageRequest) GetLanguage() string {
	if o == nil {
		return ""
	}
	return o.Language
}

type DeactivateLanguageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	LanguageActivationResponse *components.LanguageActivationResponse
}

func (o *DeactivateLanguageResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeactivateLanguageResponse) GetLanguageActivationResponse() *components.LanguageActivationResponse {
	if o == nil {
		return nil
	}
	return o.LanguageActivationResponse
}
