// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type FindAPIEndpointRequest struct {
	// The ID of the Api the ApiEndpoint belongs to.
	APIID string `pathParam:"style=simple,explode=false,name=apiID"`
	// The displayName of the ApiEndpoint to find (set by operationId from OpenAPI schema).
	DisplayName string `pathParam:"style=simple,explode=false,name=displayName"`
	// The version ID of the Api the ApiEndpoint belongs to.
	VersionID string `pathParam:"style=simple,explode=false,name=versionID"`
}

func (o *FindAPIEndpointRequest) GetAPIID() string {
	if o == nil {
		return ""
	}
	return o.APIID
}

func (o *FindAPIEndpointRequest) GetDisplayName() string {
	if o == nil {
		return ""
	}
	return o.DisplayName
}

func (o *FindAPIEndpointRequest) GetVersionID() string {
	if o == nil {
		return ""
	}
	return o.VersionID
}

type FindAPIEndpointResponse struct {
	// OK
	APIEndpoint *components.APIEndpoint
	HTTPMeta    components.HTTPMetadata `json:"-"`
}

func (o *FindAPIEndpointResponse) GetAPIEndpoint() *components.APIEndpoint {
	if o == nil {
		return nil
	}
	return o.APIEndpoint
}

func (o *FindAPIEndpointResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
