// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GenerateOpenAPISpecForAPIEndpointRequest struct {
	// The ID of the ApiEndpoint to generate an OpenAPI specification for.
	APIEndpointID string `pathParam:"style=simple,explode=false,name=apiEndpointID"`
	// The ID of the Api to generate an OpenAPI specification for.
	APIID string `pathParam:"style=simple,explode=false,name=apiID"`
	// The version ID of the Api to generate an OpenAPI specification for.
	VersionID string `pathParam:"style=simple,explode=false,name=versionID"`
}

func (o *GenerateOpenAPISpecForAPIEndpointRequest) GetAPIEndpointID() string {
	if o == nil {
		return ""
	}
	return o.APIEndpointID
}

func (o *GenerateOpenAPISpecForAPIEndpointRequest) GetAPIID() string {
	if o == nil {
		return ""
	}
	return o.APIID
}

func (o *GenerateOpenAPISpecForAPIEndpointRequest) GetVersionID() string {
	if o == nil {
		return ""
	}
	return o.VersionID
}

type GenerateOpenAPISpecForAPIEndpointResponse struct {
	// OK
	GenerateOpenAPISpecDiff *components.GenerateOpenAPISpecDiff
	HTTPMeta                components.HTTPMetadata `json:"-"`
}

func (o *GenerateOpenAPISpecForAPIEndpointResponse) GetGenerateOpenAPISpecDiff() *components.GenerateOpenAPISpecDiff {
	if o == nil {
		return nil
	}
	return o.GenerateOpenAPISpecDiff
}

func (o *GenerateOpenAPISpecForAPIEndpointResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
