// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"io"
	"mockserver/internal/sdk/models/components"
)

type GenerateRequestPostmanCollectionRequest struct {
	// The ID of the request to retrieve.
	RequestID string `pathParam:"style=simple,explode=false,name=requestID"`
}

func (o *GenerateRequestPostmanCollectionRequest) GetRequestID() string {
	if o == nil {
		return ""
	}
	return o.RequestID
}

type GenerateRequestPostmanCollectionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	PostmanCollection io.ReadCloser
}

func (o *GenerateRequestPostmanCollectionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GenerateRequestPostmanCollectionResponse) GetPostmanCollection() io.ReadCloser {
	if o == nil {
		return nil
	}
	return o.PostmanCollection
}
