// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"io"
	"mockserver/internal/sdk/models/components"
)

type GeneratePostmanCollectionRequest struct {
	// The ID of the Api to generate a Postman collection for.
	APIID string `pathParam:"style=simple,explode=false,name=apiID"`
	// The version ID of the Api to generate a Postman collection for.
	VersionID string `pathParam:"style=simple,explode=false,name=versionID"`
}

func (o *GeneratePostmanCollectionRequest) GetAPIID() string {
	if o == nil {
		return ""
	}
	return o.APIID
}

func (o *GeneratePostmanCollectionRequest) GetVersionID() string {
	if o == nil {
		return ""
	}
	return o.VersionID
}

type GeneratePostmanCollectionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	PostmanCollection io.ReadCloser
}

func (o *GeneratePostmanCollectionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GeneratePostmanCollectionResponse) GetPostmanCollection() io.ReadCloser {
	if o == nil {
		return nil
	}
	return o.PostmanCollection
}
