// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetAllAPIEndpointsRequest struct {
	// The ID of the Api to retrieve ApiEndpoints for.
	APIID string `pathParam:"style=simple,explode=false,name=apiID"`
}

func (o *GetAllAPIEndpointsRequest) GetAPIID() string {
	if o == nil {
		return ""
	}
	return o.APIID
}

type GetAllAPIEndpointsResponse struct {
	// OK
	APIEndpoints []components.APIEndpoint
	HTTPMeta     components.HTTPMetadata `json:"-"`
}

func (o *GetAllAPIEndpointsResponse) GetAPIEndpoints() []components.APIEndpoint {
	if o == nil {
		return nil
	}
	return o.APIEndpoints
}

func (o *GetAllAPIEndpointsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
