// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetBillingEmailResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	BillingEmailResponse *components.BillingEmailResponse
}

func (o *GetBillingEmailResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetBillingEmailResponse) GetBillingEmailResponse() *components.BillingEmailResponse {
	if o == nil {
		return nil
	}
	return o.BillingEmailResponse
}
