// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetBillingOperationsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	BillingOperationsResponse *components.BillingOperationsResponse
}

func (o *GetBillingOperationsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetBillingOperationsResponse) GetBillingOperationsResponse() *components.BillingOperationsResponse {
	if o == nil {
		return nil
	}
	return o.BillingOperationsResponse
}
