// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type MethodPath struct {
	Method components.HTTPMethod `queryParam:"name=method"`
	Path   string                `queryParam:"name=path"`
}

func (o *MethodPath) GetMethod() components.HTTPMethod {
	if o == nil {
		return components.HTTPMethod("")
	}
	return o.Method
}

func (o *MethodPath) GetPath() string {
	if o == nil {
		return ""
	}
	return o.Path
}

type GetCodeSamplesRequest struct {
	// The registry URL from which to retrieve the snippets.
	RegistryURL string `queryParam:"style=form,explode=true,name=registry_url"`
	// The operation IDs to retrieve snippets for.
	OperationIds []string `queryParam:"style=form,explode=true,name=operation_ids"`
	// The method paths to retrieve snippets for.
	MethodPaths []MethodPath `queryParam:"style=form,explode=true,name=method_paths"`
	// The languages to retrieve snippets for.
	Languages []string `queryParam:"style=form,explode=true,name=languages"`
}

func (o *GetCodeSamplesRequest) GetRegistryURL() string {
	if o == nil {
		return ""
	}
	return o.RegistryURL
}

func (o *GetCodeSamplesRequest) GetOperationIds() []string {
	if o == nil {
		return nil
	}
	return o.OperationIds
}

func (o *GetCodeSamplesRequest) GetMethodPaths() []MethodPath {
	if o == nil {
		return nil
	}
	return o.MethodPaths
}

func (o *GetCodeSamplesRequest) GetLanguages() []string {
	if o == nil {
		return nil
	}
	return o.Languages
}

type GetCodeSamplesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	UsageSnippets *components.UsageSnippets
}

func (o *GetCodeSamplesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetCodeSamplesResponse) GetUsageSnippets() *components.UsageSnippets {
	if o == nil {
		return nil
	}
	return o.UsageSnippets
}
