// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetChangesReportSignedURLRequest struct {
	// The checksum of the document to retrieve the signed access url for.
	DocumentChecksum string `pathParam:"style=simple,explode=false,name=documentChecksum"`
}

func (o *GetChangesReportSignedURLRequest) GetDocumentChecksum() string {
	if o == nil {
		return ""
	}
	return o.DocumentChecksum
}

// GetChangesReportSignedURLSignedAccess - OK
type GetChangesReportSignedURLSignedAccess struct {
	URL string `json:"url"`
}

func (o *GetChangesReportSignedURLSignedAccess) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

type GetChangesReportSignedURLResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	SignedAccess *GetChangesReportSignedURLSignedAccess
}

func (o *GetChangesReportSignedURLResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetChangesReportSignedURLResponse) GetSignedAccess() *GetChangesReportSignedURLSignedAccess {
	if o == nil {
		return nil
	}
	return o.SignedAccess
}
