// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetGithubSetupStateRequest struct {
	Org               string `queryParam:"style=form,explode=true,name=org"`
	Repo              string `queryParam:"style=form,explode=true,name=repo"`
	GenerateGenLockID string `queryParam:"style=form,explode=true,name=generate_gen_lock_id"`
}

func (o *GetGithubSetupStateRequest) GetOrg() string {
	if o == nil {
		return ""
	}
	return o.Org
}

func (o *GetGithubSetupStateRequest) GetRepo() string {
	if o == nil {
		return ""
	}
	return o.Repo
}

func (o *GetGithubSetupStateRequest) GetGenerateGenLockID() string {
	if o == nil {
		return ""
	}
	return o.GenerateGenLockID
}

type GetGithubSetupStateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// github setup state response
	GithubSetupStateResponse *components.GithubSetupStateResponse
}

func (o *GetGithubSetupStateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetGithubSetupStateResponse) GetGithubSetupStateResponse() *components.GithubSetupStateResponse {
	if o == nil {
		return nil
	}
	return o.GithubSetupStateResponse
}
