// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetLanguagesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GetLanguagesResponse *components.GetLanguagesResponse
}

func (o *GetLanguagesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetLanguagesResponse) GetGetLanguagesResponse() *components.GetLanguagesResponse {
	if o == nil {
		return nil
	}
	return o.GetLanguagesResponse
}
