// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetOrganizationSubscriptionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	OrganizationSubscriptionResponse *components.OrganizationSubscriptionResponse
}

func (o *GetOrganizationSubscriptionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetOrganizationSubscriptionResponse) GetOrganizationSubscriptionResponse() *components.OrganizationSubscriptionResponse {
	if o == nil {
		return nil
	}
	return o.OrganizationSubscriptionResponse
}
