// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetSchemaStoreItemRequestBody struct {
	ID *string `json:"id,omitempty"`
}

func (o *GetSchemaStoreItemRequestBody) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

type GetSchemaStoreItemResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	SchemaStoreItem *components.SchemaStoreItem
}

func (o *GetSchemaStoreItemResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetSchemaStoreItemResponse) GetSchemaStoreItem() *components.SchemaStoreItem {
	if o == nil {
		return nil
	}
	return o.SchemaStoreItem
}
