// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetTrialTargetsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	TrialTargetsResponse *components.TrialTargetsResponse
}

func (o *GetTrialTargetsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetTrialTargetsResponse) GetTrialTargetsResponse() *components.TrialTargetsResponse {
	if o == nil {
		return nil
	}
	return o.TrialTargetsResponse
}
