// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetTagsRequest struct {
	NamespaceName string `pathParam:"style=simple,explode=false,name=namespace_name"`
}

func (o *GetTagsRequest) GetNamespaceName() string {
	if o == nil {
		return ""
	}
	return o.NamespaceName
}

type GetTagsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GetTagsResponse *components.GetTagsResponse
}

func (o *GetTagsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetTagsResponse) GetGetTagsResponse() *components.GetTagsResponse {
	if o == nil {
		return nil
	}
	return o.GetTagsResponse
}
