// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetVersionMetadataRequest struct {
	// The ID of the Api to retrieve metadata for.
	APIID string `pathParam:"style=simple,explode=false,name=apiID"`
	// The version ID of the Api to retrieve metadata for.
	VersionID string `pathParam:"style=simple,explode=false,name=versionID"`
}

func (o *GetVersionMetadataRequest) GetAPIID() string {
	if o == nil {
		return ""
	}
	return o.APIID
}

func (o *GetVersionMetadataRequest) GetVersionID() string {
	if o == nil {
		return ""
	}
	return o.VersionID
}

type GetVersionMetadataResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	VersionMetadata []components.VersionMetadata
}

func (o *GetVersionMetadataResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetVersionMetadataResponse) GetVersionMetadata() []components.VersionMetadata {
	if o == nil {
		return nil
	}
	return o.VersionMetadata
}
