// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetWorkspaceSettingsGlobals struct {
	WorkspaceID *string `pathParam:"style=simple,explode=false,name=workspace_id"`
}

func (o *GetWorkspaceSettingsGlobals) GetWorkspaceID() *string {
	if o == nil {
		return nil
	}
	return o.WorkspaceID
}

type GetWorkspaceSettingsRequest struct {
	// Unique identifier of the workspace.
	WorkspaceID *string `pathParam:"style=simple,explode=false,name=workspace_id"`
}

func (o *GetWorkspaceSettingsRequest) GetWorkspaceID() *string {
	if o == nil {
		return nil
	}
	return o.WorkspaceID
}

type GetWorkspaceSettingsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	WorkspaceSettings *components.WorkspaceSettings
}

func (o *GetWorkspaceSettingsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetWorkspaceSettingsResponse) GetWorkspaceSettings() *components.WorkspaceSettings {
	if o == nil {
		return nil
	}
	return o.WorkspaceSettings
}
