// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetWorkspaceAccessRequest struct {
	// Unique identifier of the generation target.
	GenLockID *string `queryParam:"style=form,explode=true,name=genLockId"`
	// The type of the generated target.
	TargetType *string `queryParam:"style=form,explode=true,name=targetType"`
	// Skip side-effects like incrementing metrics.
	Passive *bool `queryParam:"style=form,explode=true,name=passive"`
}

func (o *GetWorkspaceAccessRequest) GetGenLockID() *string {
	if o == nil {
		return nil
	}
	return o.GenLockID
}

func (o *GetWorkspaceAccessRequest) GetTargetType() *string {
	if o == nil {
		return nil
	}
	return o.TargetType
}

func (o *GetWorkspaceAccessRequest) GetPassive() *bool {
	if o == nil {
		return nil
	}
	return o.Passive
}

type GetWorkspaceAccessResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AccessDetails *components.AccessDetails
}

func (o *GetWorkspaceAccessResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetWorkspaceAccessResponse) GetAccessDetails() *components.AccessDetails {
	if o == nil {
		return nil
	}
	return o.AccessDetails
}
