// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GithubConfigureCodeSamplesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GithubConfigureCodeSamplesResponse *components.GithubConfigureCodeSamplesResponse
}

func (o *GithubConfigureCodeSamplesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GithubConfigureCodeSamplesResponse) GetGithubConfigureCodeSamplesResponse() *components.GithubConfigureCodeSamplesResponse {
	if o == nil {
		return nil
	}
	return o.GithubConfigureCodeSamplesResponse
}
