// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// HandleStripeWebhookRequest - Stripe webhook event payload
type HandleStripeWebhookRequest struct {
}

type HandleStripeWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *HandleStripeWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
