// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type PreflightResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PreflightToken *components.PreflightToken
}

func (o *PreflightResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PreflightResponse) GetPreflightToken() *components.PreflightToken {
	if o == nil {
		return nil
	}
	return o.PreflightToken
}
