// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type QueryEventLogRequest struct {
	// The filter to apply to the query.
	Filters *components.Filters `queryParam:"serialization=json,name=filters"`
}

func (o *QueryEventLogRequest) GetFilters() *components.Filters {
	if o == nil {
		return nil
	}
	return o.Filters
}

type QueryEventLogResponse struct {
	// OK
	BoundedRequests []components.BoundedRequest
	HTTPMeta        components.HTTPMetadata `json:"-"`
}

func (o *QueryEventLogResponse) GetBoundedRequests() []components.BoundedRequest {
	if o == nil {
		return nil
	}
	return o.BoundedRequests
}

func (o *QueryEventLogResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
