// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type RevokeEmbedAccessTokenRequest struct {
	// The ID of the EmbedToken to revoke.
	TokenID string `pathParam:"style=simple,explode=false,name=tokenID"`
}

func (o *RevokeEmbedAccessTokenRequest) GetTokenID() string {
	if o == nil {
		return ""
	}
	return o.TokenID
}

type RevokeEmbedAccessTokenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *RevokeEmbedAccessTokenResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
