// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// SetVisibilityRequestBody - Namespace visibility
type SetVisibilityRequestBody struct {
	Public bool `json:"public"`
}

func (o *SetVisibilityRequestBody) GetPublic() bool {
	if o == nil {
		return false
	}
	return o.Public
}

type SetVisibilityRequest struct {
	// Namespace visibility
	RequestBody   *SetVisibilityRequestBody `request:"mediaType=application/json"`
	NamespaceName string                    `pathParam:"style=simple,explode=false,name=namespace_name"`
}

func (o *SetVisibilityRequest) GetRequestBody() *SetVisibilityRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *SetVisibilityRequest) GetNamespaceName() string {
	if o == nil {
		return ""
	}
	return o.NamespaceName
}

type SetVisibilityResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *SetVisibilityResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
