// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpsertAPIEndpointRequest struct {
	// A JSON representation of the ApiEndpoint to upsert.
	APIEndpoint components.APIEndpointInput `request:"mediaType=application/json"`
	// The ID of the ApiEndpoint to upsert.
	APIEndpointID string `pathParam:"style=simple,explode=false,name=apiEndpointID"`
	// The ID of the Api the ApiEndpoint belongs to.
	APIID string `pathParam:"style=simple,explode=false,name=apiID"`
	// The version ID of the Api the ApiEndpoint belongs to.
	VersionID string `pathParam:"style=simple,explode=false,name=versionID"`
}

func (o *UpsertAPIEndpointRequest) GetAPIEndpoint() components.APIEndpointInput {
	if o == nil {
		return components.APIEndpointInput{}
	}
	return o.APIEndpoint
}

func (o *UpsertAPIEndpointRequest) GetAPIEndpointID() string {
	if o == nil {
		return ""
	}
	return o.APIEndpointID
}

func (o *UpsertAPIEndpointRequest) GetAPIID() string {
	if o == nil {
		return ""
	}
	return o.APIID
}

func (o *UpsertAPIEndpointRequest) GetVersionID() string {
	if o == nil {
		return ""
	}
	return o.VersionID
}

type UpsertAPIEndpointResponse struct {
	// OK
	APIEndpoint *components.APIEndpoint
	HTTPMeta    components.HTTPMetadata `json:"-"`
}

func (o *UpsertAPIEndpointResponse) GetAPIEndpoint() *components.APIEndpoint {
	if o == nil {
		return nil
	}
	return o.APIEndpoint
}

func (o *UpsertAPIEndpointResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
