// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// Annotations
type Annotations struct {
	// The authors of the image
	OrgOpencontainersImageAuthors *string `json:"org.opencontainers.image.authors,omitempty"`
	// The time the image was created
	OrgOpencontainersImageCreated *string `json:"org.opencontainers.image.created,omitempty"`
	// Human-readable description of the software packaged in the image
	OrgOpencontainersImageDescription *string `json:"org.opencontainers.image.description,omitempty"`
	// The documentation URL of the image
	OrgOpencontainersImageDocumentation *string `json:"org.opencontainers.image.documentation,omitempty"`
	OrgOpencontainersImageLicenses      *string `json:"org.opencontainers.image.licenses,omitempty"`
	// Name of the reference for a target
	OrgOpencontainersImageRefName *string `json:"org.opencontainers.image.ref.name,omitempty"`
	// Source control revision identifier
	OrgOpencontainersImageRevision *string `json:"org.opencontainers.image.revision,omitempty"`
	// The URL to get source code for building the image
	OrgOpencontainersImageSource *string `json:"org.opencontainers.image.source,omitempty"`
	// Human-readable title of the image
	OrgOpencontainersImageTitle *string `json:"org.opencontainers.image.title,omitempty"`
	// The URL of the image
	OrgOpencontainersImageURL *string `json:"org.opencontainers.image.url,omitempty"`
	// Name of the distributing entity, organization or individual.
	OrgOpencontainersImageVendor *string `json:"org.opencontainers.image.vendor,omitempty"`
	// The version of the packaged software
	OrgOpencontainersImageVersion *string `json:"org.opencontainers.image.version,omitempty"`
}

func (a *Annotations) GetOrgOpencontainersImageAuthors() *string {
	if a == nil {
		return nil
	}
	return a.OrgOpencontainersImageAuthors
}

func (a *Annotations) GetOrgOpencontainersImageCreated() *string {
	if a == nil {
		return nil
	}
	return a.OrgOpencontainersImageCreated
}

func (a *Annotations) GetOrgOpencontainersImageDescription() *string {
	if a == nil {
		return nil
	}
	return a.OrgOpencontainersImageDescription
}

func (a *Annotations) GetOrgOpencontainersImageDocumentation() *string {
	if a == nil {
		return nil
	}
	return a.OrgOpencontainersImageDocumentation
}

func (a *Annotations) GetOrgOpencontainersImageLicenses() *string {
	if a == nil {
		return nil
	}
	return a.OrgOpencontainersImageLicenses
}

func (a *Annotations) GetOrgOpencontainersImageRefName() *string {
	if a == nil {
		return nil
	}
	return a.OrgOpencontainersImageRefName
}

func (a *Annotations) GetOrgOpencontainersImageRevision() *string {
	if a == nil {
		return nil
	}
	return a.OrgOpencontainersImageRevision
}

func (a *Annotations) GetOrgOpencontainersImageSource() *string {
	if a == nil {
		return nil
	}
	return a.OrgOpencontainersImageSource
}

func (a *Annotations) GetOrgOpencontainersImageTitle() *string {
	if a == nil {
		return nil
	}
	return a.OrgOpencontainersImageTitle
}

func (a *Annotations) GetOrgOpencontainersImageURL() *string {
	if a == nil {
		return nil
	}
	return a.OrgOpencontainersImageURL
}

func (a *Annotations) GetOrgOpencontainersImageVendor() *string {
	if a == nil {
		return nil
	}
	return a.OrgOpencontainersImageVendor
}

func (a *Annotations) GetOrgOpencontainersImageVersion() *string {
	if a == nil {
		return nil
	}
	return a.OrgOpencontainersImageVersion
}
