// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type BillingAddOn string

const (
	BillingAddOnWebhooks          BillingAddOn = "webhooks"
	BillingAddOnSDKTesting        BillingAddOn = "sdk_testing"
	BillingAddOnCustomCodeRegions BillingAddOn = "custom_code_regions"
	BillingAddOnSnippetAi         BillingAddOn = "snippet_ai"
)

func (e BillingAddOn) ToPointer() *BillingAddOn {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *BillingAddOn) IsExact() bool {
	if e != nil {
		switch *e {
		case "webhooks", "sdk_testing", "custom_code_regions", "snippet_ai":
			return true
		}
	}
	return false
}
