// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type BusinessTierPriceResponse struct {
	// The currency code (e.g., usd)
	Currency string `json:"currency"`
	// The billing interval (e.g., month)
	Interval string `json:"interval"`
	// The Stripe price ID
	PriceID string `json:"price_id"`
	// The product name from Stripe
	ProductName string `json:"product_name"`
	// The price amount in cents
	UnitAmount int64 `json:"unit_amount"`
}

func (b *BusinessTierPriceResponse) GetCurrency() string {
	if b == nil {
		return ""
	}
	return b.Currency
}

func (b *BusinessTierPriceResponse) GetInterval() string {
	if b == nil {
		return ""
	}
	return b.Interval
}

func (b *BusinessTierPriceResponse) GetPriceID() string {
	if b == nil {
		return ""
	}
	return b.PriceID
}

func (b *BusinessTierPriceResponse) GetProductName() string {
	if b == nil {
		return ""
	}
	return b.ProductName
}

func (b *BusinessTierPriceResponse) GetUnitAmount() int64 {
	if b == nil {
		return 0
	}
	return b.UnitAmount
}
