// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// BillingInterval - Billing interval (defaults to month)
type BillingInterval string

const (
	BillingIntervalMonth BillingInterval = "month"
	BillingIntervalYear  BillingInterval = "year"
)

func (e BillingInterval) ToPointer() *BillingInterval {
	return &e
}
func (e *BillingInterval) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "month":
		fallthrough
	case "year":
		*e = BillingInterval(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BillingInterval: %v", v)
	}
}

type CreateLanguageCheckoutSessionRequest struct {
	// Billing interval (defaults to month)
	BillingInterval *BillingInterval `json:"billing_interval,omitempty"`
	// URL to redirect to if checkout is canceled
	CancelURL string `json:"cancel_url"`
	// List of languages to activate
	Languages []string `json:"languages"`
	// URL to redirect to on successful checkout
	SuccessURL string `json:"success_url"`
}

func (c *CreateLanguageCheckoutSessionRequest) GetBillingInterval() *BillingInterval {
	if c == nil {
		return nil
	}
	return c.BillingInterval
}

func (c *CreateLanguageCheckoutSessionRequest) GetCancelURL() string {
	if c == nil {
		return ""
	}
	return c.CancelURL
}

func (c *CreateLanguageCheckoutSessionRequest) GetLanguages() []string {
	if c == nil {
		return []string{}
	}
	return c.Languages
}

func (c *CreateLanguageCheckoutSessionRequest) GetSuccessURL() string {
	if c == nil {
		return ""
	}
	return c.SuccessURL
}
