// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetLanguagesResponse struct {
	// List of language billing configurations
	Languages []LanguageResponse `json:"languages"`
}

func (g *GetLanguagesResponse) GetLanguages() []LanguageResponse {
	if g == nil {
		return []LanguageResponse{}
	}
	return g.Languages
}
