// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetTagsResponse struct {
	Items []Tag `json:"items"`
}

func (g *GetTagsResponse) GetItems() []Tag {
	if g == nil {
		return []Tag{}
	}
	return g.Items
}
