// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// GithubConfigureCodeSamplesRequest - A request to configure GitHub code samples
type GithubConfigureCodeSamplesRequest struct {
	// The GitHub organization name
	Org string `json:"org"`
	// The GitHub repository name
	Repo string `json:"repo"`
	// The target name for the code samples
	TargetName string `json:"targetName"`
}

func (g *GithubConfigureCodeSamplesRequest) GetOrg() string {
	if g == nil {
		return ""
	}
	return g.Org
}

func (g *GithubConfigureCodeSamplesRequest) GetRepo() string {
	if g == nil {
		return ""
	}
	return g.Repo
}

func (g *GithubConfigureCodeSamplesRequest) GetTargetName() string {
	if g == nil {
		return ""
	}
	return g.TargetName
}
