// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// GithubConfigureCodeSamplesResponse - A response to configure GitHub code samples
type GithubConfigureCodeSamplesResponse struct {
	// The URL of the code sample overlay registry
	CodeSampleOverlayRegistryURL string `json:"codeSampleOverlayRegistryURL"`
	// The ID of the GitHub action that was dispatched
	GhActionID *string `json:"ghActionID,omitempty"`
	// A document referenced by a workflow
	Source WorkflowDocument `json:"source"`
}

func (g *GithubConfigureCodeSamplesResponse) GetCodeSampleOverlayRegistryURL() string {
	if g == nil {
		return ""
	}
	return g.CodeSampleOverlayRegistryURL
}

func (g *GithubConfigureCodeSamplesResponse) GetGhActionID() *string {
	if g == nil {
		return nil
	}
	return g.GhActionID
}

func (g *GithubConfigureCodeSamplesResponse) GetSource() WorkflowDocument {
	if g == nil {
		return WorkflowDocument{}
	}
	return g.Source
}
