// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Actions struct {
	GenerationActionConfigured bool `json:"generation_action_configured"`
	PublishActionConfigured    bool `json:"publish_action_configured"`
}

func (a *Actions) GetGenerationActionConfigured() bool {
	if a == nil {
		return false
	}
	return a.GenerationActionConfigured
}

func (a *Actions) GetPublishActionConfigured() bool {
	if a == nil {
		return false
	}
	return a.PublishActionConfigured
}

type Secrets struct {
	APIKeyConfigured            bool `json:"api_key_configured"`
	PublishingSecretsConfigured bool `json:"publishing_secrets_configured"`
}

func (s *Secrets) GetAPIKeyConfigured() bool {
	if s == nil {
		return false
	}
	return s.APIKeyConfigured
}

func (s *Secrets) GetPublishingSecretsConfigured() bool {
	if s == nil {
		return false
	}
	return s.PublishingSecretsConfigured
}

// GithubSetupStateResponse - The state of a particular SDK targets github setup
type GithubSetupStateResponse struct {
	Actions      Actions `json:"actions"`
	AppInstalled bool    `json:"app_installed"`
	Secrets      Secrets `json:"secrets"`
}

func (g *GithubSetupStateResponse) GetActions() Actions {
	if g == nil {
		return Actions{}
	}
	return g.Actions
}

func (g *GithubSetupStateResponse) GetAppInstalled() bool {
	if g == nil {
		return false
	}
	return g.AppInstalled
}

func (g *GithubSetupStateResponse) GetSecrets() Secrets {
	if g == nil {
		return Secrets{}
	}
	return g.Secrets
}
