// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/utils"
	"time"
)

// PendingCancellationInfo - Information about a pending subscription cancellation
type PendingCancellationInfo struct {
	// When the cancellation takes effect (from Stripe current_period_end)
	EffectiveAt *time.Time `json:"effective_at,omitempty"`
	// gen_lock_id of the target that will be kept after downgrade
	TargetToKeep *string `json:"target_to_keep,omitempty"`
	// Display name of the target to keep
	TargetToKeepName *string `json:"target_to_keep_name,omitempty"`
}

func (p PendingCancellationInfo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PendingCancellationInfo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PendingCancellationInfo) GetEffectiveAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.EffectiveAt
}

func (p *PendingCancellationInfo) GetTargetToKeep() *string {
	if p == nil {
		return nil
	}
	return p.TargetToKeep
}

func (p *PendingCancellationInfo) GetTargetToKeepName() *string {
	if p == nil {
		return nil
	}
	return p.TargetToKeepName
}
