// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/utils"
	"time"
)

type TargetResource string

const (
	TargetResourceDocument TargetResource = "document"
)

func (e TargetResource) ToPointer() *TargetResource {
	return &e
}
func (e *TargetResource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "document":
		*e = TargetResource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TargetResource: %v", v)
	}
}

// PublishingToken - A token used to publish to a target
type PublishingToken struct {
	CreatedAt      time.Time      `json:"created_at"`
	CreatedBy      string         `json:"created_by"`
	ID             string         `json:"id"`
	OrganizationID string         `json:"organization_id"`
	TargetID       string         `json:"target_id"`
	TargetResource TargetResource `json:"target_resource"`
	Token          string         `json:"token"`
	TokenName      string         `json:"token_name"`
	UpdatedAt      *time.Time     `json:"updated_at,omitempty"`
	UpdatedBy      *string        `json:"updated_by,omitempty"`
	ValidUntil     time.Time      `json:"valid_until"`
	WorkspaceID    string         `json:"workspace_id"`
}

func (p PublishingToken) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublishingToken) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublishingToken) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *PublishingToken) GetCreatedBy() string {
	if p == nil {
		return ""
	}
	return p.CreatedBy
}

func (p *PublishingToken) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublishingToken) GetOrganizationID() string {
	if p == nil {
		return ""
	}
	return p.OrganizationID
}

func (p *PublishingToken) GetTargetID() string {
	if p == nil {
		return ""
	}
	return p.TargetID
}

func (p *PublishingToken) GetTargetResource() TargetResource {
	if p == nil {
		return TargetResource("")
	}
	return p.TargetResource
}

func (p *PublishingToken) GetToken() string {
	if p == nil {
		return ""
	}
	return p.Token
}

func (p *PublishingToken) GetTokenName() string {
	if p == nil {
		return ""
	}
	return p.TokenName
}

func (p *PublishingToken) GetUpdatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.UpdatedAt
}

func (p *PublishingToken) GetUpdatedBy() *string {
	if p == nil {
		return nil
	}
	return p.UpdatedBy
}

func (p *PublishingToken) GetValidUntil() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.ValidUntil
}

func (p *PublishingToken) GetWorkspaceID() string {
	if p == nil {
		return ""
	}
	return p.WorkspaceID
}
