// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// RelativeDiff - A relative diff between the current revision and the previous revision.
type RelativeDiff struct {
	// The number of lines added against the previous revision
	AddedLines *int64 `json:"added_lines,omitempty"`
	// The number of lines removed against the previous revision
	RemovedLines *int64 `json:"removed_lines,omitempty"`
}

func (r *RelativeDiff) GetAddedLines() *int64 {
	if r == nil {
		return nil
	}
	return r.AddedLines
}

func (r *RelativeDiff) GetRemovedLines() *int64 {
	if r == nil {
		return nil
	}
	return r.RemovedLines
}
