// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// RemoteSource - Remote source configuration
type RemoteSource struct {
	Inputs []RemoteDocument `json:"inputs"`
	// A document hosted in the registry
	Output   RemoteDocument   `json:"output"`
	Overlays []RemoteDocument `json:"overlays,omitempty"`
}

func (r *RemoteSource) GetInputs() []RemoteDocument {
	if r == nil {
		return []RemoteDocument{}
	}
	return r.Inputs
}

func (r *RemoteSource) GetOutput() RemoteDocument {
	if r == nil {
		return RemoteDocument{}
	}
	return r.Output
}

func (r *RemoteSource) GetOverlays() []RemoteDocument {
	if r == nil {
		return nil
	}
	return r.Overlays
}
