// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/utils"
	"time"
)

type RevisionContentsMetadataType string

const (
	RevisionContentsMetadataTypeOpenapiBundle  RevisionContentsMetadataType = "OPENAPI_BUNDLE"
	RevisionContentsMetadataTypeOpenapiOverlay RevisionContentsMetadataType = "OPENAPI_OVERLAY"
)

func (e RevisionContentsMetadataType) ToPointer() *RevisionContentsMetadataType {
	return &e
}
func (e *RevisionContentsMetadataType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "OPENAPI_BUNDLE":
		fallthrough
	case "OPENAPI_OVERLAY":
		*e = RevisionContentsMetadataType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RevisionContentsMetadataType: %v", v)
	}
}

type RevisionContentsMetadata struct {
	// Whether the OAS contains code samples.
	ContainsCodeSamples bool      `json:"contains_code_samples"`
	CreatedAt           time.Time `json:"created_at"`
	// The OAS description
	Description string `json:"description"`
	// The hash of the contents
	Hash string `json:"hash"`
	// The fully qualified namespace
	Namespace string `json:"namespace"`
	// The number of overlay actions in the OAS. Will be 0 if the OAS is not an overlay.
	NumOverlayActions int64 `json:"num_overlay_actions"`
	// The operation IDs contained in the OAS. Will be empty if the OAS is an overlay.
	OperationIds []string `json:"operation_ids"`
	// A relative diff between the current revision and the previous revision.
	RelativeDiff *RelativeDiff `json:"relative_diff,omitempty"`
	// The digest of the parent bundle
	RevisionDigest string `json:"revision_digest"`
	// The servers contained in the OAS. Will be empty if the OAS is an overlay.
	ServerUrls []Server `json:"server_urls"`
	// The tags contained in the OAS -- NOT the OCI tags. Will be empty if the OAS is an overlay.
	Tags []string `json:"tags"`
	// The OAS title
	Title string                       `json:"title"`
	Type  RevisionContentsMetadataType `json:"type"`
	// The OAS version
	Version string `json:"version"`
	// The workspace ID
	WorkspaceID string `json:"workspace_id"`
}

func (r RevisionContentsMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RevisionContentsMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RevisionContentsMetadata) GetContainsCodeSamples() bool {
	if r == nil {
		return false
	}
	return r.ContainsCodeSamples
}

func (r *RevisionContentsMetadata) GetCreatedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.CreatedAt
}

func (r *RevisionContentsMetadata) GetDescription() string {
	if r == nil {
		return ""
	}
	return r.Description
}

func (r *RevisionContentsMetadata) GetHash() string {
	if r == nil {
		return ""
	}
	return r.Hash
}

func (r *RevisionContentsMetadata) GetNamespace() string {
	if r == nil {
		return ""
	}
	return r.Namespace
}

func (r *RevisionContentsMetadata) GetNumOverlayActions() int64 {
	if r == nil {
		return 0
	}
	return r.NumOverlayActions
}

func (r *RevisionContentsMetadata) GetOperationIds() []string {
	if r == nil {
		return []string{}
	}
	return r.OperationIds
}

func (r *RevisionContentsMetadata) GetRelativeDiff() *RelativeDiff {
	if r == nil {
		return nil
	}
	return r.RelativeDiff
}

func (r *RevisionContentsMetadata) GetRevisionDigest() string {
	if r == nil {
		return ""
	}
	return r.RevisionDigest
}

func (r *RevisionContentsMetadata) GetServerUrls() []Server {
	if r == nil {
		return []Server{}
	}
	return r.ServerUrls
}

func (r *RevisionContentsMetadata) GetTags() []string {
	if r == nil {
		return []string{}
	}
	return r.Tags
}

func (r *RevisionContentsMetadata) GetTitle() string {
	if r == nil {
		return ""
	}
	return r.Title
}

func (r *RevisionContentsMetadata) GetType() RevisionContentsMetadataType {
	if r == nil {
		return RevisionContentsMetadataType("")
	}
	return r.Type
}

func (r *RevisionContentsMetadata) GetVersion() string {
	if r == nil {
		return ""
	}
	return r.Version
}

func (r *RevisionContentsMetadata) GetWorkspaceID() string {
	if r == nil {
		return ""
	}
	return r.WorkspaceID
}
