// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// SSOMetadata - SSO metadata for a workspace
type SSOMetadata struct {
	SsoActivated bool     `json:"sso_activated"`
	SsoDomains   []string `json:"sso_domains"`
}

func (s *SSOMetadata) GetSsoActivated() bool {
	if s == nil {
		return false
	}
	return s.SsoActivated
}

func (s *SSOMetadata) GetSsoDomains() []string {
	if s == nil {
		return []string{}
	}
	return s.SsoDomains
}
