// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Tag struct {
	// Format {namespace_id}/{tag}
	ID string `json:"id"`
	// Human readable tag name
	Name           string `json:"name"`
	NamespaceName  string `json:"namespace_name"`
	RevisionDigest string `json:"revision_digest"`
}

func (t *Tag) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *Tag) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *Tag) GetNamespaceName() string {
	if t == nil {
		return ""
	}
	return t.NamespaceName
}

func (t *Tag) GetRevisionDigest() string {
	if t == nil {
		return ""
	}
	return t.RevisionDigest
}
