// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/utils"
	"time"
)

// TargetSDKSummary - Lean representation of a target with only the fields needed by the dashboard UI. Excludes large fields like workflow YAML files to reduce response payload size.
type TargetSDKSummary struct {
	// Name of the CI environment.
	ContinuousIntegrationEnvironment *string `json:"continuous_integration_environment,omitempty"`
	// Version of the generated target (post generation)
	GenerateConfigPostVersion *string `json:"generate_config_post_version,omitempty"`
	// gen.lock ID (expected to be a uuid). A unique identifier for the target.
	GenerateGenLockID string `json:"generate_gen_lock_id"`
	// Features prior to generation
	GenerateGenLockPreFeatures *string `json:"generate_gen_lock_pre_features,omitempty"`
	// Artifact version for the Previous Generation
	GenerateGenLockPreVersion *string `json:"generate_gen_lock_pre_version,omitempty"`
	// Indicates whether the target was considered published.
	GeneratePublished *bool `json:"generate_published,omitempty"`
	// eg `typescript`, `terraform`, `python`
	GenerateTarget string `json:"generate_target"`
	// The workflow name of the target.
	GenerateTargetName *string `json:"generate_target_name,omitempty"`
	// GitHub organization of the action.
	GhActionOrganization *string `json:"gh_action_organization,omitempty"`
	// GitHub repository of the action.
	GhActionRepository *string `json:"gh_action_repository,omitempty"`
	// Link to the GitHub action run.
	GhActionRunLink *string `json:"gh_action_run_link,omitempty"`
	// Current working directory relative to the git root.
	GitRelativeCwd *string `json:"git_relative_cwd,omitempty"`
	// Default owner for git remote.
	GitRemoteDefaultOwner *string `json:"git_remote_default_owner,omitempty"`
	// Default repository name for git remote.
	GitRemoteDefaultRepo *string `json:"git_remote_default_repo,omitempty"`
	// User email from git configuration.
	GitUserEmail *string `json:"git_user_email,omitempty"`
	// User's name from git configuration. (not GitHub username)
	GitUserName *string `json:"git_user_name,omitempty"`
	// Remote hostname.
	Hostname *string `json:"hostname,omitempty"`
	// Unique identifier of the target, same as generate_gen_lock_id
	ID string `json:"id"`
	// Timestamp when the event was created in the database.
	LastEventCreatedAt time.Time `json:"last_event_created_at"`
	// Name of the published package.
	PublishPackageName *string `json:"publish_package_name,omitempty"`
	// Name of the registry where the package was published.
	PublishPackageRegistryName *string `json:"publish_package_registry_name,omitempty"`
	// URL of the published package.
	PublishPackageURL *string `json:"publish_package_url,omitempty"`
	// Version of the published package.
	PublishPackageVersion *string `json:"publish_package_version,omitempty"`
	// The namespace name of the source.
	SourceNamespaceName *string `json:"source_namespace_name,omitempty"`
}

func (t TargetSDKSummary) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TargetSDKSummary) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TargetSDKSummary) GetContinuousIntegrationEnvironment() *string {
	if t == nil {
		return nil
	}
	return t.ContinuousIntegrationEnvironment
}

func (t *TargetSDKSummary) GetGenerateConfigPostVersion() *string {
	if t == nil {
		return nil
	}
	return t.GenerateConfigPostVersion
}

func (t *TargetSDKSummary) GetGenerateGenLockID() string {
	if t == nil {
		return ""
	}
	return t.GenerateGenLockID
}

func (t *TargetSDKSummary) GetGenerateGenLockPreFeatures() *string {
	if t == nil {
		return nil
	}
	return t.GenerateGenLockPreFeatures
}

func (t *TargetSDKSummary) GetGenerateGenLockPreVersion() *string {
	if t == nil {
		return nil
	}
	return t.GenerateGenLockPreVersion
}

func (t *TargetSDKSummary) GetGeneratePublished() *bool {
	if t == nil {
		return nil
	}
	return t.GeneratePublished
}

func (t *TargetSDKSummary) GetGenerateTarget() string {
	if t == nil {
		return ""
	}
	return t.GenerateTarget
}

func (t *TargetSDKSummary) GetGenerateTargetName() *string {
	if t == nil {
		return nil
	}
	return t.GenerateTargetName
}

func (t *TargetSDKSummary) GetGhActionOrganization() *string {
	if t == nil {
		return nil
	}
	return t.GhActionOrganization
}

func (t *TargetSDKSummary) GetGhActionRepository() *string {
	if t == nil {
		return nil
	}
	return t.GhActionRepository
}

func (t *TargetSDKSummary) GetGhActionRunLink() *string {
	if t == nil {
		return nil
	}
	return t.GhActionRunLink
}

func (t *TargetSDKSummary) GetGitRelativeCwd() *string {
	if t == nil {
		return nil
	}
	return t.GitRelativeCwd
}

func (t *TargetSDKSummary) GetGitRemoteDefaultOwner() *string {
	if t == nil {
		return nil
	}
	return t.GitRemoteDefaultOwner
}

func (t *TargetSDKSummary) GetGitRemoteDefaultRepo() *string {
	if t == nil {
		return nil
	}
	return t.GitRemoteDefaultRepo
}

func (t *TargetSDKSummary) GetGitUserEmail() *string {
	if t == nil {
		return nil
	}
	return t.GitUserEmail
}

func (t *TargetSDKSummary) GetGitUserName() *string {
	if t == nil {
		return nil
	}
	return t.GitUserName
}

func (t *TargetSDKSummary) GetHostname() *string {
	if t == nil {
		return nil
	}
	return t.Hostname
}

func (t *TargetSDKSummary) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TargetSDKSummary) GetLastEventCreatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.LastEventCreatedAt
}

func (t *TargetSDKSummary) GetPublishPackageName() *string {
	if t == nil {
		return nil
	}
	return t.PublishPackageName
}

func (t *TargetSDKSummary) GetPublishPackageRegistryName() *string {
	if t == nil {
		return nil
	}
	return t.PublishPackageRegistryName
}

func (t *TargetSDKSummary) GetPublishPackageURL() *string {
	if t == nil {
		return nil
	}
	return t.PublishPackageURL
}

func (t *TargetSDKSummary) GetPublishPackageVersion() *string {
	if t == nil {
		return nil
	}
	return t.PublishPackageVersion
}

func (t *TargetSDKSummary) GetSourceNamespaceName() *string {
	if t == nil {
		return nil
	}
	return t.SourceNamespaceName
}
