// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type WorkspaceSettings struct {
	WebhookURL  *string `json:"webhook_url,omitempty"`
	WorkspaceID string  `json:"workspace_id"`
}

func (o *WorkspaceSettings) GetWebhookURL() *string {
	if o == nil {
		return nil
	}
	return o.WebhookURL
}

func (o *WorkspaceSettings) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}
