// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// WorkspaceFeatureFlagRequest - A request to add workspace feature flags
type WorkspaceFeatureFlagRequest struct {
	FeatureFlags []WorkspaceFeatureFlag `json:"feature_flags"`
}

func (w *WorkspaceFeatureFlagRequest) GetFeatureFlags() []WorkspaceFeatureFlag {
	if w == nil {
		return []WorkspaceFeatureFlag{}
	}
	return w.FeatureFlags
}
