// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/utils"
	"time"
)

// Workspace - A speakeasy workspace
type Workspace struct {
	CreatedAt      time.Time `json:"created_at"`
	ID             string    `json:"id"`
	Inactive       *bool     `json:"inactive,omitempty"`
	Name           string    `json:"name"`
	OrganizationID string    `json:"organization_id"`
	Slug           string    `json:"slug"`
	// Deprecated. Use organization.telemetry_disabled instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	TelemetryDisabled *bool     `json:"telemetry_disabled,omitempty"`
	UpdatedAt         time.Time `json:"updated_at"`
	Verified          bool      `json:"verified"`
}

func (w Workspace) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *Workspace) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *Workspace) GetCreatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.CreatedAt
}

func (w *Workspace) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

func (w *Workspace) GetInactive() *bool {
	if w == nil {
		return nil
	}
	return w.Inactive
}

func (w *Workspace) GetName() string {
	if w == nil {
		return ""
	}
	return w.Name
}

func (w *Workspace) GetOrganizationID() string {
	if w == nil {
		return ""
	}
	return w.OrganizationID
}

func (w *Workspace) GetSlug() string {
	if w == nil {
		return ""
	}
	return w.Slug
}

func (w *Workspace) GetTelemetryDisabled() *bool {
	if w == nil {
		return nil
	}
	return w.TelemetryDisabled
}

func (w *Workspace) GetUpdatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.UpdatedAt
}

func (w *Workspace) GetVerified() bool {
	if w == nil {
		return false
	}
	return w.Verified
}
