// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// WorkspaceFeatureFlagResponse - Workspace feature flag response
type WorkspaceFeatureFlagResponse struct {
	FeatureFlags []FeatureFlag `json:"feature_flags,omitempty"`
}

func (w *WorkspaceFeatureFlagResponse) GetFeatureFlags() []FeatureFlag {
	if w == nil {
		return nil
	}
	return w.FeatureFlags
}
