workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://www.speakeasy.com/openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/my-source
targets:
    speakeasy-client-sdk-go:
        target: go
        source: my-source
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/code-samples-go-speakeasy-client-sdk-go
