name: Generate
"on":
    workflow_dispatch:
        inputs:
            force:
                description: Force generation of SDKs
                type: boolean
                default: false
            push_code_samples_only:
                description: Force push only code samples from SDK generation
                type: boolean
                default: false
    schedule:
        # This sets the workflow to run every day at 3:00 PM PST (10:00 PM UTC)
        - cron: '0 22 * * *'
jobs:
    generate:
        uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
        with:
            force: ${{ github.event.inputs.force }}
            mode: pr
            speakeasy_version: latest
        secrets:
            github_access_token: ${{ secrets.GITHUB_TOKEN }}
            slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
            speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
