name: Speakeasy Testing
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  Go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - run: curl -fsSL https://go.speakeasy.com/cli-install.sh | sh
      - run: speakeasy test
        env:
          SPEAKEASY_API_KEY: ${{ secrets.SPEAKEASY_API_KEY }}
